name: tir_sportif

description: >
  Application mobile pour suivre les entraînements de tir sportif.

publish_to: 'none'

version: 0.1.0

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  sqflite: ^2.3.0
  path_provider: ^2.1.2
  intl: ^0.19.0
  fl_chart: ^1.1.1
  http: ^1.5.0
  flutter_markdown: ^0.7.7+1
  yaml: ^3.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/fftir_logo.png
    - assets/app_logo.png
    - assets/coach_prompt.yaml
    - assets/config.yaml
